# Form implementation generated from reading ui file '/home/grossmj/PycharmProjects/gns3-webclient-pack/gns3_webclient_pack/ui/command_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_uiCommandDialog(object):
    def setupUi(self, uiCommandDialog):
        uiCommandDialog.setObjectName("uiCommandDialog")
        uiCommandDialog.resize(685, 377)
        uiCommandDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(uiCommandDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=uiCommandDialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.uiCommandComboBox = QtWidgets.QComboBox(parent=uiCommandDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiCommandComboBox.sizePolicy().hasHeightForWidth())
        self.uiCommandComboBox.setSizePolicy(sizePolicy)
        self.uiCommandComboBox.setObjectName("uiCommandComboBox")
        self.horizontalLayout.addWidget(self.uiCommandComboBox)
        self.uiRemovePushButton = QtWidgets.QPushButton(parent=uiCommandDialog)
        self.uiRemovePushButton.setObjectName("uiRemovePushButton")
        self.horizontalLayout.addWidget(self.uiRemovePushButton)
        self.uiSavePushButton = QtWidgets.QPushButton(parent=uiCommandDialog)
        self.uiSavePushButton.setObjectName("uiSavePushButton")
        self.horizontalLayout.addWidget(self.uiSavePushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label = QtWidgets.QLabel(parent=uiCommandDialog)
        self.label.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.uiCommandPlainTextEdit = QtWidgets.QPlainTextEdit(parent=uiCommandDialog)
        self.uiCommandPlainTextEdit.setMinimumSize(QtCore.QSize(500, 0))
        self.uiCommandPlainTextEdit.setObjectName("uiCommandPlainTextEdit")
        self.verticalLayout.addWidget(self.uiCommandPlainTextEdit)
        self.uiButtonBox = QtWidgets.QDialogButtonBox(parent=uiCommandDialog)
        self.uiButtonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.uiButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Help|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.uiButtonBox.setObjectName("uiButtonBox")
        self.verticalLayout.addWidget(self.uiButtonBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(uiCommandDialog)
        self.uiButtonBox.accepted.connect(uiCommandDialog.accept) # type: ignore
        self.uiButtonBox.rejected.connect(uiCommandDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(uiCommandDialog)

    def retranslateUi(self, uiCommandDialog):
        _translate = QtCore.QCoreApplication.translate
        uiCommandDialog.setWindowTitle(_translate("uiCommandDialog", "Command"))
        self.label_2.setText(_translate("uiCommandDialog", "Choose a predefined command:"))
        self.uiRemovePushButton.setText(_translate("uiCommandDialog", "&Remove"))
        self.uiSavePushButton.setText(_translate("uiCommandDialog", "&Save"))
        self.label.setText(_translate("uiCommandDialog", "<html><head/><body><p>Or customize the current command:</p></body></html>"))
